server:
  port: 10000
zuul:
  routes:
    cunstom1:
      path: custom1/**
      serviceId: custom1
    cunstom2:
      path: custom2/**
      serviceId: custom2
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 500
  MaxAutoRetries: 1 #当前实例的超时重试次数
  MaxAutoRetriesNextServer: 2 #其他实例超时重试次数。这是统一配置，针对所有的微服务。如果是单独的。在各自的微服务中配置。
  eureka:
    enabled: false
spring:
  application:
    name: service-zuul
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #超时设置
#robbon:
#   ConnectTimeout: 6000
#   ReadTimeout: 6000