
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liu948114632/springcloud-config
  application:
    name: service-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
server:
  port: 8888
